name: Build Keychron B1 Pro JIS Custom Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: West Init
        run: west init -l app/
      
      - name: West Update
        run: west update
      
      - name: West Zephyr Export
        run: west zephyr-export
      
      - name: West Build (Keychron B1 JIS)
        run: west build -s app -b nice60 -- -DSHIELD=keychron_b1_jis -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      
      - name: Rename firmware
        run: |
          mkdir -p artifacts
          cp build/zephyr/zmk.uf2 artifacts/keychron_b1_jis_custom.uf2
      
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: keychron-b1-jis-firmware
          path: artifacts/ 